Added GetDrugExposureEndDate function
JuliaHealth/OMOPCDMCohortCreator.jl pull request #71
Opened 2024-01-04 16:34 UTC by Jay-sanjay

This PR is related to #69 

## PR CheckList

- [ ]  Added GetDrugExposureEndDate function
- [ ]  Added doc-strings and test-suite for it

2024-01-06 18:36 UTC, TheCedarPrince requested changes
Just a few changes mostly to documentation. Also, could you add a reference to this function in the API page of the documentation?

Thanks and great work on this -- you made this super straightforward and nice to review!

2024-01-06 18:36 UTC, TheCedarPrince commented on src/getters.jl
> +function GetDrugExposureEndDate(drug_exposure_ids; tab = drug_exposure)
Could you add the `conn` argument into this docstring?

2024-01-06 18:36 UTC, TheCedarPrince commented on src/getters.jl
> +Given a list of drug_exposure IDs, find their corresponding drug_exposure_end_date ID.
I'd say instead:

"Given a list of drug_exposure IDs, find their exposure end dates."

2024-01-06 18:36 UTC, TheCedarPrince commented on src/getters.jl
> +`:drug_exposure_end_date` corresponding to a given `drug_exposure_id` and `drug_exposure_end_date` in the `DataFrame`
I'd rewrite this as:

Given a `DataFrame` with a `:drug_exposure_id` column, return the `DataFrame` with an associated 
`:drug_exposure_end_date` corresponding to a given `drug_exposure_id` in the `DataFrame`.

2024-01-06 18:36 UTC, TheCedarPrince commented on src/getters.jl
> +- `df::DataFrame` - a two column `DataFrame` comprised of columns: `:drug_exposure_id` and `:drug_exposure_end_date`
This will return the SQL statement -- could you update this?

2024-01-15 03:39 UTC, TheCedarPrince approved these changes
LGTM! Feel free to merge.

Question: Do you still want to explore another PR that improves code coverage separately? Or did you want to try exploring that further in this PR?

2024-01-15 03:52 UTC, Jay-sanjay commented
@TheCedarPrince  yes that might be a good idea,I can file an issue for it. Because if in case I won't able to add that for all function, then also the issue would be present for the future work.

2024-01-15 03:53 UTC, merged